### ISSUE TITLE
Problem with the project

### ISSUE THREAD

**Issue by L4ma** [Young-Development/music-library#3]
![grafik](https://cloud.githubusercontent.com/assets/26965333/25804133/8557ea4e-33fa-11e7-8b7f-71eb3d816fd7.png)

Problem with the project!!

**Comment by m3a3r9c9** [comment]
I addet the Javafx libary to the project. You need go into your jdk folder and add this jar. You can find the jar in Java/jdk/jre/lib/ext/jfxrt    
Add it like JavaKara

**Comment by m3a3r9c9** [comment]
![libary](https://cloud.githubusercontent.com/assets/28427259/25804435/127afa0a-33fc-11e7-9ec9-f163cd0b72e7.PNG)
